apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: farid-nginx
  name: farid-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farid-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: farid-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
