apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: farid-nginx
  name: farid-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: farid-nginx
  type: LoadBalancer
status:
  loadBalancer: {}
