apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu-test
  name: ubuntu-test
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: ubuntu
    name: ubuntu-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
